### GENERAL SETTINGS ###

# Site settings
title: Belle Software (UK)
description: "Enterprise-level Software Development and Architecture Services for Java and Perl"
# analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://bellesoftware.uk"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#f70031" 
  primary_rgb: "247,0,49" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#000000"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url:
  - title: twitter
    url:
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: info@bellesoftware.uk
tel: +44 793one 53226one

### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Ashley Hindmarsh
    position: Director/CTO/whatever
    text: Ashley has over 25 years experience learning about software development across many domains.
    img: ashley-chanrio.png
    social:
      - title: envelope #use for email address
        url: mailto:ashley@bellesoftware.uk
      - title: twitter
        url: http://twitter.com/ashbelle
      - title: file-pdf-o
        url: /ash-cv/cv2015.contract.pdf
      - title: html5
        url: /ash-cv/cv2015.contract.html
      - title: file-word-o
        url: /ash-cv/cv2015.contract.docx
  - name: Tracy Hindmarsh
    position: Secretary
    text: Tracy keeps the books in good shape and is the first contact for clients
    img: tracy-chanrio.png
    social:
      - title: envelope #use for email address
        url: mailto:tracy@bellesoftware.uk
    
# Clients information. Shown on Home and About pages.
clients:
  - name: BBC
    img: bbc_logo_large.jpg
  - name: Sky
    img: sky_logo.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Belle Software and predecessors have been providing Java and Perl software and architecture in various guises since 1995."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: X
    position: Y

